config/routes.rb
Rails.application.routes.draw do
  resources :notices

  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'notices#index'

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notices
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /notices
  # GET /notices.json

  def index
    @notices = Notice.all.order("created_at desc")
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:titile, :description, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :ulab_id, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :ulab_id, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/registrations_controller_helper.rb
module RegistrationsControllerHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UlabNoticeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "mystyle.css" %>
</head>
<body>


<div id="login">
<%= yield %>
</div>
</body>
</html>

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h1>Create/Update Notice</h1>

    <%= f.text_field :titile, class: "login-input", placeholder: "Title", required: true  %>

    <%= f.text_field :description, class: "login-input", placeholder: "Description", required: true %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div><%= f.submit "Create/Update Notice", class:"login-submit" %></div>

    <p class="login-help"><a href="/notices">Back</a></p>
<% end %>

app/views/notices/edit.html.erb
<%= render 'form' %>

app/views/notices/index.html.erb
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

<br><br>




<style>
    body {
        font: 12px/1.4 Arial, Helvetica, sans-serif;
        color: #333;
        margin: 0;
        padding: 0;
    }

    table {
        border-collapse: collapse;
        padding: 0;
        margin: 0 0 11px 0;
        width: 100%;
    }

    table th {
        text-align: left;
        border-bottom: 2px solid #eee;
        vertical-align: bottom;
        padding: 0 10px 10px 10px;
        text-align: right;
    }

    table td {
        border-bottom: 1px solid #eee;
        vertical-align: top;
        padding: 10px;
        text-align: right;

    }

    table th:nth-child(1),
    table td:nth-child(1) {
        text-align: left;
        padding-left: 0;
        font-weight: bold;
        color: #0000ff;
    }
    /* responsive table */
@media screen and (max-width: 480px) {
    table,
    thead,
    tbody {
        display: block;
        width: 100%:
    }
    table td {
        border: none;
        margin-bottom: 6px;
       
    }

    .td_table{

        color: #0000ff;
    }

    }

    .table_style{

        background-color: #ffffff;
        margin: 3px;
        
    }

    #h11
    {
        font-size: 2em;
        margin: 2px;
    }

    
    

</style>
<h1 id="h11">All Notice</h1>

<br>

<table class="table_style">

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td id="morar_link" class="td_table" data-title="Title"><%= link_to notice.titile, notice %></td>
        <td> Posted by </td>
        <td data-title="Name"><%= notice.user.name %></td>
        <% t = notice.created_at + 6.hours %>
        <td data-title="Published at"><%= "#{distance_of_time_in_words(Time.now, notice.created_at)} ago" %></td>
        
        <% if notice.user_id == current_user.id %>
            <td data-title="Modify"><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/notices/new.html.erb
<%= render 'form' %>

app/views/notices/show.html.erb
<style>
   

</style>
<p id="notice"><%= notice %></p>

<p id="title_notice">
  <%= @notice.titile %>
</p>
<br>
<p id="title_des">
  <strong>Description:</strong><br>
  <%= @notice.description %>
</p>
<p id="title_name">
  <strong>Name:</strong>
  <%= @notice.user.name %>
</p>
<%= button_to "Edit", edit_notice_path(@notice), :method => "get" %>
<br>
<%= button_to "Back", notices_path, :method => "get" %>